<?php

use Illuminate\Database\Seeder;


class MajorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arc_prodi = array(
		  array('id' => '1','code' => '101','name' => 'Matematika'),
		  array('id' => '2','code' => '201','name' => 'Matematika'),
		  array('id' => '3','code' => '301','name' => 'Matematika'),
		  array('id' => '4','code' => '901','name' => 'Pengajaran Matematika'),
		  array('id' => '5','code' => '102','name' => 'Fisika'),
		  array('id' => '6','code' => '202','name' => 'Fisika'),
		  array('id' => '7','code' => '302','name' => 'Fisika'),
		  array('id' => '8','code' => '902','name' => 'Pengajaran Fisika'),
		  array('id' => '9','code' => '103','name' => 'Astronomi'),
		  array('id' => '10','code' => '203','name' => 'Astronomi'),
		  array('id' => '11','code' => '303','name' => 'Astronomi'),
		  array('id' => '12','code' => '105','name' => 'Kimia'),
		  array('id' => '13','code' => '205','name' => 'Kimia'),
		  array('id' => '14','code' => '305','name' => 'Kimia'),
		  array('id' => '15','code' => '905','name' => 'Pengajaran Kimia'),
		  array('id' => '16','code' => '208','name' => 'Aktuaria'),
		  array('id' => '17','code' => '209','name' => 'Sains Komputasi'),
		  array('id' => '18','code' => '160','name' => 'Tahap Tahun Pertama FMIPA'),
		  array('id' => '19','code' => '104','name' => 'Mikrobiologi'),
		  array('id' => '20','code' => '106','name' => 'Biologi'),
		  array('id' => '21','code' => '206','name' => 'Biologi'),
		  array('id' => '22','code' => '306','name' => 'Biologi'),
		  array('id' => '23','code' => '211','name' => 'Bioteknologi'),
		  array('id' => '24','code' => '112','name' => 'Rekayasa Hayati'),
		  array('id' => '25','code' => '213','name' => 'Biomanajemen'),
		  array('id' => '26','code' => '114','name' => 'Rekayasa Pertanian'),
		  array('id' => '27','code' => '115','name' => 'Rekayasa Kehutanan'),
		  array('id' => '28','code' => '119','name' => 'Teknologi Pasca Panen'),
		  array('id' => '29','code' => '161','name' => 'Tahap Tahun Pertama SITH - Program Sains'),
		  array('id' => '30','code' => '198','name' => 'Tahap Tahun Pertama SITH - Program Rekayasa'),
		  array('id' => '31','code' => '107','name' => 'Sains dan Teknologi Farmasi'),
		  array('id' => '32','code' => '207','name' => 'Farmasi'),
		  array('id' => '33','code' => '307','name' => 'Farmasi'),
		  array('id' => '34','code' => '907','name' => 'Profesi Apoteker'),
		  array('id' => '35','code' => '116','name' => 'Farmasi Klinik dan Komunitas'),
		  array('id' => '36','code' => '217','name' => 'Keolahragaan'),
		  array('id' => '37','code' => '218','name' => 'Farmasi Industri'),
		  array('id' => '38','code' => '162','name' => 'Tahap Tahun Pertama SF'),
		  array('id' => '39','code' => '121','name' => 'Teknik Pertambangan'),
		  array('id' => '40','code' => '221','name' => 'Rekayasa Pertambangan'),
		  array('id' => '41','code' => '321','name' => 'Rekayasa Pertambangan'),
		  array('id' => '42','code' => '122','name' => 'Teknik Perminyakan'),
		  array('id' => '43','code' => '222','name' => 'Teknik Perminyakan'),
		  array('id' => '44','code' => '322','name' => 'Teknik Perminyakan'),
		  array('id' => '45','code' => '123','name' => 'Teknik Geofisika'),
		  array('id' => '46','code' => '223','name' => 'Teknik Geofisika'),
		  array('id' => '47','code' => '323','name' => 'Teknik Geofisika'),
		  array('id' => '48','code' => '125','name' => 'Teknik Metalurgi'),
		  array('id' => '49','code' => '226','name' => 'Teknik Panas Bumi'),
		  array('id' => '50','code' => '164','name' => 'Tahap Tahun Pertama FTTM'),
		  array('id' => '51','code' => '120','name' => 'Teknik Geologi'),
		  array('id' => '52','code' => '220','name' => 'Teknik Geologi'),
		  array('id' => '53','code' => '320','name' => 'Teknik Geologi'),
		  array('id' => '54','code' => '224','name' => 'Sains Kebumian'),
		  array('id' => '55','code' => '324','name' => 'Sains Kebumian'),
		  array('id' => '56','code' => '227','name' => 'Teknik Air Tanah'),
		  array('id' => '57','code' => '128','name' => 'Meteorologi'),
		  array('id' => '58','code' => '129','name' => 'Oseanografi'),
		  array('id' => '59','code' => '151','name' => 'Teknik Geodesi dan Geomatika'),
		  array('id' => '60','code' => '251','name' => 'Teknik Geodesi dan Geomatika'),
		  array('id' => '61','code' => '351','name' => 'Teknik Geodesi dan Geomatika'),
		  array('id' => '62','code' => '951','name' => 'Administrasi Pertanahan'),
		  array('id' => '63','code' => '163','name' => 'Tahap Tahun Pertama FITB'),
		  array('id' => '64','code' => '130','name' => 'Teknik Kimia'),
		  array('id' => '65','code' => '230','name' => 'Teknik Kimia'),
		  array('id' => '66','code' => '330','name' => 'Teknik Kimia'),
		  array('id' => '67','code' => '133','name' => 'Teknik Fisika'),
		  array('id' => '68','code' => '233','name' => 'Teknik Fisika'),
		  array('id' => '69','code' => '333','name' => 'Teknik Fisika'),
		  array('id' => '70','code' => '134','name' => 'Teknik Industri'),
		  array('id' => '71','code' => '234','name' => 'Teknik dan Manajemen Industri'),
		  array('id' => '72','code' => '334','name' => 'Teknik dan Manajemen Industri'),
		  array('id' => '73','code' => '238','name' => 'Instrumentasi dan Kontrol'),
		  array('id' => '74','code' => '143','name' => 'Teknik Pangan'),
		  array('id' => '75','code' => '144','name' => 'Manajemen Rekayasa Industri'),
		  array('id' => '76','code' => '145','name' => 'Teknik Bioenergi dan Kemurgi'),
		  array('id' => '77','code' => '945','name' => 'Logistik'),
		  array('id' => '78','code' => '167','name' => 'Tahap Tahun Pertama FTI'),
		  array('id' => '79','code' => '195','name' => 'Tahap Tahun Pertama FTI - Jatinangor'),
		  array('id' => '80','code' => '132','name' => 'Teknik Elektro'),
		  array('id' => '81','code' => '232','name' => 'Teknik Elektro'),
		  array('id' => '82','code' => '332','name' => 'Teknik Elektro dan Informatika'),
		  array('id' => '83','code' => '135','name' => 'Teknik Informatika'),
		  array('id' => '84','code' => '235','name' => 'Informatika'),
		  array('id' => '85','code' => '165','name' => 'Tahap Tahun Pertama STEI'),
		  array('id' => '86','code' => '180','name' => 'Teknik Tenaga Listrik'),
		  array('id' => '87','code' => '181','name' => 'Teknik Telekomunikasi'),
		  array('id' => '88','code' => '182','name' => 'Sistem dan Teknologi Informasi'),
		  array('id' => '89','code' => '183','name' => 'Teknik Biomedis'),
		  array('id' => '90','code' => '131','name' => 'Teknik Mesin'),
		  array('id' => '91','code' => '231','name' => 'Teknik Mesin'),
		  array('id' => '92','code' => '331','name' => 'Teknik Mesin'),
		  array('id' => '93','code' => '136','name' => 'Aeronotika dan Astronotika'),
		  array('id' => '94','code' => '236','name' => 'Aeronotika dan Astronotika'),
		  array('id' => '95','code' => '336','name' => 'Aeronotika dan Astronotika'),
		  array('id' => '96','code' => '137','name' => 'Teknik Material'),
		  array('id' => '97','code' => '237','name' => 'Ilmu dan Teknik Material'),
		  array('id' => '98','code' => '337','name' => 'Ilmu dan Teknik Material'),
		  array('id' => '99','code' => '249','name' => 'Ilmu dan Rekayasa Nuklir'),
		  array('id' => '100','code' => '349','name' => 'Rekayasa Nuklir'),
		  array('id' => '101','code' => '169','name' => 'Tahap Tahun Pertama FTMD'),
		  array('id' => '102','code' => '150','name' => 'Teknik Sipil'),
		  array('id' => '103','code' => '250','name' => 'Teknik Sipil'),
		  array('id' => '104','code' => '350','name' => 'Teknik Sipil'),
		  array('id' => '105','code' => '950','name' => 'Pengelolaan Sumberdaya Air'),
		  array('id' => '106','code' => '153','name' => 'Teknik Lingkungan'),
		  array('id' => '107','code' => '253','name' => 'Teknik Lingkungan'),
		  array('id' => '108','code' => '353','name' => 'Teknik Lingkungan'),
		  array('id' => '109','code' => '155','name' => 'Teknik Kelautan'),
		  array('id' => '110','code' => '255','name' => 'Teknik Kelautan'),
		  array('id' => '111','code' => '157','name' => 'Rekayasa Infrastruktur Lingkungan'),
		  array('id' => '112','code' => '257','name' => 'Pengelolaan Infrastruktur Air Bersih dan Sanitasi'),
		  array('id' => '113','code' => '158','name' => 'Teknik dan Pengelolaan Sumber Daya Air'),
		  array('id' => '114','code' => '166','name' => 'Tahap Tahun Pertama FTSL'),
		  array('id' => '115','code' => '269','name' => 'Sistem dan Teknik Jalan Raya'),
		  array('id' => '116','code' => '196','name' => 'Tahap Tahun Pertama FTSL - Jatinangor'),
		  array('id' => '117','code' => '239','name' => 'Studi Pertahanan'),
		  array('id' => '118','code' => '240','name' => 'Studi Pembangunan'),
		  array('id' => '119','code' => '242','name' => 'Transportasi'),
		  array('id' => '120','code' => '342','name' => 'Transportasi'),
		  array('id' => '121','code' => '152','name' => 'Arsitektur'),
		  array('id' => '122','code' => '252','name' => 'Arsitektur'),
		  array('id' => '123','code' => '352','name' => 'Arsitektur'),
		  array('id' => '124','code' => '154','name' => 'Perencanaan Wilayah dan Kota'),
		  array('id' => '125','code' => '254','name' => 'Perencanaan Wilayah dan Kota'),
		  array('id' => '126','code' => '354','name' => 'Perencanaan Wilayah dan Kota'),
		  array('id' => '127','code' => '256','name' => 'Rancang Kota'),
		  array('id' => '128','code' => '957','name' => 'Terapan Perencanaan Kepariwisataan'),
		  array('id' => '129','code' => '289','name' => 'Arsitektur Lanskap'),
		  array('id' => '130','code' => '199','name' => 'Tahap Tahun Pertama SAPPK'),
		  array('id' => '131','code' => '168','name' => 'Tahap Tahun Pertama FSRD'),
		  array('id' => '132','code' => '170','name' => 'Seni Rupa'),
		  array('id' => '133','code' => '270','name' => 'Seni Rupa'),
		  array('id' => '134','code' => '370','name' => 'Ilmu Seni Rupa dan Desain'),
		  array('id' => '135','code' => '271','name' => 'Desain'),
		  array('id' => '136','code' => '172','name' => 'Kriya'),
		  array('id' => '137','code' => '173','name' => 'Desain Interior'),
		  array('id' => '138','code' => '174','name' => 'Desain Komunikasi Visual'),
		  array('id' => '139','code' => '175','name' => 'Desain Produk'),
		  array('id' => '140','code' => '179','name' => 'MKDU'),
		  array('id' => '141','code' => '190','name' => 'Manajemen'),
		  array('id' => '142','code' => '290','name' => 'Sains Manajemen'),
		  array('id' => '143','code' => '390','name' => 'Sains Manajemen'),
		  array('id' => '144','code' => '291','name' => 'Administrasi Bisnis'),
		  array('id' => '145','code' => '192','name' => 'Kewirausahaan'),
		  array('id' => '146','code' => '293','name' => 'Administrasi Bisnis'),
		  array('id' => '147','code' => '197','name' => 'Tahap Tahun Pertama SBM')
		);

		foreach ($arc_prodi as $key => $value) {
	            \App\Major::create($value);
	        }
    }
}

